language: elixir

elixir:
  - 1.11

otp_release:
  - 21

env:
  global:
    - MIX_ENV=test

notifications:
  email: false

sudo: false

script:
  - mix test


after_script:
   - MIX_ENV=docs mix deps.get